### ISSUE TITLE
pull docker image

### ISSUE THREAD

**Issue by feliu** [akrabat/ow-php-docker#1]
I cant see how you pull the docker image to docker hub or anything. You repo is not possible to replicate

**Comment by akrabat** [comment]
This example uses the standard OpenWhisk docker image so it doesn't use Docker hub itself. OpenWhisk's cli tool `wsk` recently changed, so you now use `--native` for this functionality.

I've updated this repo accordingly.

Running `./build.sh`, I get this:

```
$ ./build.sh phpaction
Updating dependencies
Creating Zip file
Updating OpenWhisk action 'phpaction'
Invoking OpenWhisk action: wsk action invoke -br phpaction --param name Everyone
{
    "Uuid": "a6fbe4e3-4e74-43c1-a935-f8b712822797",
    "greeting": "Hello Everyone!",
    "time": "Sat, 22 Jul 2017 07:59:11 +0000"
}
```
